# Candace Savonen 2021
# Updated April 2025

# This workflow was adapted by Carrie Wright to enable automated rendering of the site associated with this repository
# This code now incorporates adaptation by Ava Hoffman to build a collection on a schedule

# +---------------- minute (0 - 59)
# |  +------------- hour (0 - 23)
# |  |  +---------- day of month (1 - 31)
# |  |  |  +------- month (1 - 12)
# |  |  |  |  +---- day of week (0 - 6) (Sunday=0 or 7)
# |  |  |  |  |
# *  *  *  *  *  command to be executed

name: Render website

# Controls when the action will run. Triggers the workflow on push
# events only for the main branch

on:
  workflow_dispatch:
  schedule:
  - cron: "0 3 * * 0"
  push:
    branches: [ main ]
    paths:
      - '**.Rmd'
      - styles.css
      - _site.yml
      - resources/images/*.png
      - resources/images/favicon.ico
      - resources/collection.tsv

jobs:

  yaml-check:
    name: Load user automation choices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Use the yaml-env-action action.
      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: config_automation.yml # Pass a space-separated list of configuration files. Rightmost files take precedence.
    outputs:
      toggle_website: "${{ env.RENDER_WEBSITE }}"
      rendering_docker_image: "${{ env.RENDERING_DOCKER_IMAGE }}"

  build-collection:
    name: Build Collection
    needs: yaml-check
    uses: ./.github/workflows/build-collection.yml
    with:
      render-type: 'main'
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}

  render-website:
    name: Render website
    needs: [yaml-check, build-collection]
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Run render
        id: render
        uses: ottrproject/ottr-preview@main
        with:
          toggle_website: ${{needs.yaml-check.outputs.toggle_website}}
          preview: false
          token: ${{ secrets.GH_PAT }}
          docker_image: ${{needs.yaml-check.outputs.rendering_docker_image}}
